// shared/constants/permissions.js
// Hem frontend hem backend tarafından import edilebilir.

export const PERMISSIONS = {
  USERS_READ:   "USERS_READ",
  USERS_WRITE:  "USERS_WRITE",

  SERVICES_READ:  "SERVICES_READ",
  SERVICES_WRITE: "SERVICES_WRITE",

  SCHEDULE_READ:  "SCHEDULE_READ",
  SCHEDULE_WRITE: "SCHEDULE_WRITE",

  LEAVES_READ:  "LEAVES_READ",
  LEAVES_WRITE: "LEAVES_WRITE",

  PARAMETERS_READ:  "PARAMETERS_READ",
  PARAMETERS_WRITE: "PARAMETERS_WRITE",

  EXPORT_IMPORT: "EXPORT_IMPORT",
};
