"use strict";

/**
 * Shared V3 composite reason codes.
 */
const COMPOSITE_REASON_CODES = Object.freeze({
  COMPOSITE_WORK_AREA_NOT_ELIGIBLE: "COMPOSITE_WORK_AREA_NOT_ELIGIBLE",
  COMPOSITE_NO_REQUIRED_AREA_MATCH: "COMPOSITE_NO_REQUIRED_AREA_MATCH",
  COMPOSITE_TASK_PLACE_NOT_COMPOSITE: "COMPOSITE_TASK_PLACE_NOT_COMPOSITE",
});

module.exports = COMPOSITE_REASON_CODES;
