"use strict";

const REASON_CODES = Object.freeze({
  PERSON_ID_MISSING: "PERSON_ID_MISSING",
  DATE_MISSING: "DATE_MISSING",
  ROLE_REQUIREMENT_MISSING: "ROLE_REQUIREMENT_MISSING",
  PERSON_ROLE_MISSING_FAIL_CLOSED: "PERSON_ROLE_MISSING_FAIL_CLOSED",
  TARGET_SECTION_MISSING: "TARGET_SECTION_MISSING",
  PERSON_SECTION_MISSING_FAIL_CLOSED: "PERSON_SECTION_MISSING_FAIL_CLOSED",
  SECTION_NOT_ALLOWED: "SECTION_NOT_ALLOWED",
  SERVICE_ID_MISSING: "SERVICE_ID_MISSING",
  PERSON_SERVICE_MISSING: "PERSON_SERVICE_MISSING",
  SAME_DAY_ASSIGNMENT_FOUND: "SAME_DAY_ASSIGNMENT_FOUND",
  REST_AFTER_NIGHT_VIOLATION: "REST_AFTER_NIGHT_VIOLATION",
  MAX_WEEKLY_SHIFTS_EXCEEDED: "MAX_WEEKLY_SHIFTS_EXCEEDED",
  MAX_CONSECUTIVE_DAYS_EXCEEDED: "MAX_CONSECUTIVE_DAYS_EXCEEDED",
  RULE_NOT_REGISTERED: "RULE_NOT_REGISTERED",
  RULE_EXECUTION_ERROR: "RULE_EXECUTION_ERROR",
  PERSON_MISSING: "PERSON_MISSING",
  PREVIOUS_DATE_CALCULATION_FAILED: "PREVIOUS_DATE_CALCULATION_FAILED",
  TASK_PLACE_NOT_SECTION: "TASK_PLACE_NOT_SECTION",
  TASK_PLACE_COMPOSITE: "TASK_PLACE_COMPOSITE",
  TASK_PLACE_UNKNOWN: "TASK_PLACE_UNKNOWN",
  COMPOSITE_WORK_AREA_CONFIG_MISSING: "COMPOSITE_WORK_AREA_CONFIG_MISSING",
  COMPOSITE_WORK_AREA_NOT_ELIGIBLE: "COMPOSITE_WORK_AREA_NOT_ELIGIBLE",
});

module.exports = REASON_CODES;
